# Continuous Integration and Deployment of Utopia Models Repository
---
# ++ Pipeline preparations ++++++++++++++++++++++++++++++++++++++++++++++++++++
variables:
  # Which Utopia base image to use
  UTOPIA_BASE_IMAGE: ccees/utopia-base:eoan-v1

  # Which repo to use for the framework and which branch to clone from
  UTOPIA_CLONE_URL: https://ts-gitlab.iup.uni-heidelberg.de/utopia/utopia.git
  # NOTE This should always be the master; change this only for testing!
  UTOPIA_BRANCH: master

  # Subdirectory inside project directory to use for framework repository
  UTOPIA_DIR: _framework

  # Variables for Models Docker image deployment
  VERTEX_MODEL_BASE_IMAGE_NAME: ccees/vertex-model-base
  VERTEX_MODEL_BASE_IMAGE_TAG: "1.0"
  VERTEX_MODEL_BASE_IMAGE: "${VERTEX_MODEL_BASE_IMAGE_NAME}:v${VERTEX_MODEL_BASE_IMAGE_TAG}"
  # NOTE Do not forget to increment the VERTEX_MODEL_BASE_IMAGE_TAG when changes
  #      to the docker file are introduced.

  # Docker Hub login command
  DOCKER_HUB_LOGIN: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PW
  # NOTE Both variables here are secret and protected variables. While the
  #      login command will complain, using --password-stdin actually EXPOSES
  #      the variable! No no.

  # Setting number of processes for build jobs and DIND jobs
  CPUS_BUILD: 4
  CPUS_TEST: 4

  # Global compiler flags
  # NOTE: This should improve the test runtime but might lead to erroneous
  #       coverage reports.
  # NOTE: This will also be applied to the debug build.
  CXXFLAGS: -Og

  # Build flags
  MAKE_FLAGS_BUILD: -j$CPUS_BUILD
  MAKE_FLAGS_TEST: -j$CPUS_TEST

  # ... for certain commands
  RUN_IN_UTOPIA_ENV: $CI_PROJECT_DIR/build/run-in-utopia-env
  ENTER_UTOPIA_ENV: source $CI_PROJECT_DIR/build/activate


# Define the image to use for all stages
image: ${VERTEX_MODEL_BASE_IMAGE}

stages:
  - setup     # set up the Docker base image for testing
  - prep      # prepare the utopia framework repo and configure utopia
  - build     # build models and tests
  - test      # carry out tests
  - report    # Compile reports on testing


# .. YAML Templates ...........................................................
# This makes includes below easier using the `<<: *anchor_name` syntax

# Create artifacts of the build directory
.artifacts: &artifacts
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/.config        # copied from ~/.config
      - $CI_PROJECT_DIR/.cmake         # copied from ~/.cmake
      - $CI_PROJECT_DIR/build          # created in build stage
      - $CI_PROJECT_DIR/$UTOPIA_DIR    # framework paths (setup stage)
    expire_in: 3 hours


# Use the Docker-in-Docker executor and services, log into Docker Hub
.dind: &dind
  image: docker:stable
  tags:
    - dind
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - $DOCKER_HUB_LOGIN


# ++ Job definitions ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# -- Setup stage --------------------------------------------------------------
# This stage takes care to build the Models base testing image

setup:vertex-model-base:
  <<: *dind
  stage: setup
  only:
    - master
    - web
  script:
    - docker build -f docker/vertex-model-base.dockerfile
                   --build-arg UTOPIA_BASE_IMAGE=$UTOPIA_BASE_IMAGE
                   -t $VERTEX_MODEL_BASE_IMAGE
                   ./
    - docker push $VERTEX_MODEL_BASE_IMAGE

# -- Preparation stage --------------------------------------------------------
# This stage sets up the Utopa framework, the main dependency of this repo

prep:framework:
  <<: [*artifacts]
  stage: prep
  script:
    # Clone the framework repo to a specific directory and check out the
    # desired branch. By cloning into a subdirectory inside the project
    # directory, artifacts can be used.
    - git clone --recurse-submodules -b $UTOPIA_BRANCH $UTOPIA_CLONE_URL $UTOPIA_DIR

    # Create build directory and configure
    - cd $UTOPIA_DIR && mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..

    # Now, move back to the project directory and configure, specifying the
    # Utopia directory.
    - cd $CI_PROJECT_DIR && mkdir build && cd build
    - cmake
      -DUtopia_DIR=$CI_PROJECT_DIR/$UTOPIA_DIR/build
      -DCPP_COVERAGE=On
      ..

    # Show available models
    - $RUN_IN_UTOPIA_ENV utopia models ls

    # Carry over user config directory (to have it available in artifacts)
    - cp -r ~/.config $CI_PROJECT_DIR/

    # Carry over CMake package registry
    - cp -r ~/.cmake $CI_PROJECT_DIR/

# -- Build stage --------------------------------------------------------------
# In this stage, the models and their tests are built.
# The artifacts of the tests and models jobs are needed in the test stage

# Build the models and their tests; artifacts used in test stage
build:all: &build
  <<: *artifacts
  stage: build
  dependencies:
    - prep:framework
  before_script:
    # Copy the frontend-generated configuration, carried over as artifacts,
    # back into the home directory, where the frontend expects it.
    # In the same manner, place the cmake registry where it is expected.
    - &copy_config_to_home cp -r $CI_PROJECT_DIR/.config ~/
    - &copy_cmake_reg_to_home cp -r $CI_PROJECT_DIR/.cmake ~/
  script:
    - cd $CI_PROJECT_DIR/build
    - make $MAKE_FLAGS_BUILD build_tests_models
    - make $MAKE_FLAGS_BUILD all

# Build in debug mode, once with gcc and once with clang
build:debug: &build_debug
  <<: *build
  allow_failure: true
  before_script:
    - *copy_config_to_home
    - *copy_cmake_reg_to_home
    - cd $CI_PROJECT_DIR/build
    - cmake
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_CXX_FLAGS_DEBUG='-Werror -Wall -Wextra'
      ..

build:debug-clang:
  <<: *build_debug
  before_script:
    - *copy_config_to_home
    - *copy_cmake_reg_to_home
    - cd $CI_PROJECT_DIR/build
    - cmake
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_CXX_FLAGS_DEBUG='-Werror -Wall -Wextra'
      ..

# Build the documentation; artifacts retained for verification
build:docs:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/build/doc
    expire_in: 1 week
    expose_as: Documentation
  script:
    - cd build
    - make doc


# -- Test stage ---------------------------------------------------------------
# Using the artifacts of the build stage, execute the model tests

# Perform the explicit model tests, C++ and Python
test:models: &model_defaults
  <<: *artifacts
  stage: test
  dependencies:
    - build:all
  needs:
    - build:all
  before_script:
    - *copy_config_to_home
    - *copy_cmake_reg_to_home
  script:
    # Test all models using the testing framework
    - cd build
    - make $MAKE_FLAGS_TEST test_models


# Run each model via the CLI, testing default model and plots configuration
test:model_defaults:
  <<: *model_defaults
  dependencies:
    - build:all
  needs:
    - build:all
  script:
    - $ENTER_UTOPIA_ENV

    - utopia run NotchDelta --debug
    - utopia run PCPVertex --debug
    - utopia run PCPTopology --debug --num-steps 5

    # NOTE Add your newly implemented model here (in alphabetical order)


# -- Report stage ---------------------------------------------------------------
# Using the artifacts of the test stage, compile reports on the tests

# Install gcovr and extract coverage reports
report:coverage:
  stage: report
  variables:
    # Limit report to models repo, exclude any paths containing 'test'
    GCOVR_PATHS:
      --root $CI_PROJECT_DIR
      --filter $CI_PROJECT_DIR/src/models
      --exclude '.*[Tt]est.*'
  script:
    - source $CI_PROJECT_DIR/build/activate
    - pip3 install gcovr
    - cd $CI_PROJECT_DIR/build
    - mkdir coverage
    # Run once for report in HTML format
    - gcovr $GCOVR_PATHS --html --html-details -o coverage/report.html
    # Run again for coverage report in GitLab
    - gcovr $GCOVR_PATHS
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    name: "$CI_JOB_NAME"
    expose_as: Coverage report
    paths:
      - $CI_PROJECT_DIR/build/coverage/
    expire_in: 1 week
